Раздел 2. Структуры данных
htmlacademy-ecmascript/684117-big-trip-simple-19 pull request #4
Opened 2022-12-12 09:28 UTC by EgorBaydashev

2022-12-12 15:02 UTC, Dima-Dim requested changes

2022-12-12 15:02 UTC, Dima-Dim commented on src/const.js
> +const TYPES = ["taxi", "bus", "train", "ship", "drive", "flight", "check-in", "sightseeing", "restaurant"];
Можно чуть конкретизировать название.

2022-12-12 15:02 UTC, Dima-Dim commented on src/mock/point.js
> +const mockPoints = [
Можно так, можно рандомизировать количество элементов массива и всех его составных частей.

2022-12-12 15:02 UTC, Dima-Dim commented on src/model/points-model.js
> +  points = Array.from({length: POINT_COUNT}, getRandomPoint);
Лучше передавать как значение аргумента этого класса.

2022-12-12 15:02 UTC, Dima-Dim commented on src/presenter/list-presenter.js
> +    for (let i = 0; i < this.listPoints.length; i++) {
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2022-12-12 15:03 UTC, Dima-Dim reviewed
Не забывать про замечания линтера.

2022-12-12 16:47 UTC, EgorBaydashev commented on src/model/points-model.js
> +  points = Array.from({length: POINT_COUNT}, getRandomPoint);
Не понял про что речь( Сделал как в Лайве

2022-12-12 16:56 UTC, EgorBaydashev commented on src/const.js
> +const TYPES = ["taxi", "bus", "train", "ship", "drive", "flight", "check-in", "sightseeing", "restaurant"];
сделал

2022-12-12 16:57 UTC, EgorBaydashev commented on src/mock/point.js
> +const mockPoints = [
оставил как есть

2022-12-12 17:12 UTC, EgorBaydashev commented on src/presenter/list-presenter.js
> +    for (let i = 0; i < this.listPoints.length; i++) {
сделал как в Лайве, так как позже мы будем итерироваться не с первого элемента. В будущем ForEach не подойдет

2022-12-13 07:08 UTC, Dima-Dim commented on src/model/points-model.js
> +  points = Array.from({length: POINT_COUNT}, getRandomPoint);
Речь про то, что класс может принимать аргумены и за счёт этого можно управлять, например, тем сколько будет точек отрисовано.

2022-12-22 04:06 UTC, merged